apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: civo-private-jd4-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: civo-private-jd4 description
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  destinations:
  - name: in-cluster
    namespace: civo-private-jd4-environment
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: civo-private-jd4-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:civo-private-jd4:admin-role, applications, *, civo-private-jd4/*, allow
