apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-preprod-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: aws-preprod description
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  destinations:
  - name: in-cluster
    namespace: aws-preprod-environment
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: aws-preprod-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:aws-preprod:admin-role, applications, *, aws-preprod/*, allow
