apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: virtual-dev-cluster-2-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: virtual-dev-cluster-2 description
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  destinations:
  - name: in-cluster
    namespace: virtual-dev-cluster-2-environment
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: virtual-dev-cluster-2-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:virtual-dev-cluster-2:admin-role, applications, *, virtual-dev-cluster-2/*, allow
