apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-gitlab-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: test-gitlab description
  sourceRepos:
  - 'https://github.com/barclays-corp/barclays-corp-gitops.git'
  destinations:
  - name: in-cluster
    namespace: test-gitlab-environment
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: test-gitlab-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:test-gitlab:admin-role, applications, *, test-gitlab/*, allow
