apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testt-environment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: testt description
  sourceRepos:
  - "https://github.com/gitops-ing/team-gitops-repo"
  destinations:
  - name: in-cluster
    namespace: testt-environment
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: testt-admin-role
    groups:
    - admins
    name: admin-role
    policies:
    - p, proj:testt:admin-role, applications, *, testt/*, allow
---
