apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: civo-private-run-jd3
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-bu-mgmt-mgmt-barclays-corp"
          key      = "registry/clusters/civo-private-run-jd3/infrastructure/provider-config/terraform.tfstate"
          region = "us-west-2"
          encrypt = true
        }
        required_providers {
          civo = {
            source  = "civo/civo"
            version = "= 1.1.0"
          }
          aws = {
            source = "hashicorp/aws"
            version = ">= 5.30.0, < 6.0.0"
          }
        }
      }
      provider "aws" {
        alias  = "PROJECT_REGION"
        region = "us-west-2"
        allowed_account_ids = ["555935582951"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "arn:aws:iam::555935582951:role/crossplane-mgmt-barclays-corp"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "civo" {
        credentials_file = "civo.json"
        region = "barclays-lon1"
      }
  credentials:
  - filename: civo.json
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: civo-preprod-civo-creds
      key: config.json
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
