apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civo-public-dryrun-jd6-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: civo-public-dryrun-jd6-platform
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |-
        controller:
          podAnnotations:
            linkerd.io/inject: enabled
          ingressClass: nginx
          publishService:
            enabled: true
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    name: civo-public-dryrun-jd6
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
