apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-devops-provider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: 0
spec:
  project: default
  source:
    repoURL: https://github.com/gitops-ing/barclays-corp-gitops
    path: registry/iac/s3-devops/provider-config
    targetRevision: HEAD
  destination:
    name: <no value>
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        maxDuration: 15m0s
        factor: 2
